apiVersion: v1
kind: Service
metadata:
  name: dscheduler
  labels:
    name: dscheduler
spec:
  ports:
    - port: 8786
      targetPort: 8786
      name: dscheduler-tcp
    - port: 9786
      targetPort: 9786
      name: dscheduler-http
  selector:
    name: dscheduler
---
apiVersion: v1
kind: Service
metadata:
  name: dscheduler-status
  labels:
    name: dscheduler-status
spec:
  type: LoadBalancer
  ports:
    - port: 8787
      targetPort: 8787
  selector:
    name: dscheduler
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: dscheduler
  name: dscheduler
spec:
  replicas: 1
  selector:
    name: dscheduler
  template:
    metadata:
      labels:
        name: dscheduler
    spec:
      containers:
        - name: dscheduler
          image: kforeman/distributed:latest
          args: ["start-dscheduler.sh"]
          ports:
          - name: rpc
            containerPort: 8786
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: dworker
  name: dworker
spec:
  replicas: 3
  selector:
    name: dworker
  template:
    metadata:
      labels:
        name: dworker
    spec:
      containers:
        - name: dworker
          image: kforeman/distributed:latest
          args: ["start-dworker.sh"]
